'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MultiImageLoader
    
    '''<summary>
    '''pnlMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMulti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pclAttachPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pclAttachPhoto As Global.iBoltz.MultipleImageUpLoader.PhotoUploader
    
    '''<summary>
    '''hidUploadedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidUploadedFiles As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnGetUploadedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetUploadedFiles As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptUploaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUploaded As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblPhotoCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhotoCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSavePhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePhoto As Global.System.Web.UI.WebControls.Button
End Class
